import { mkdirSync } from 'node:fs'
import { chromium } from 'playwright'

const baseUrl = process.env.ARC_BASE_URL ?? 'http://127.0.0.1:4173'
const evidenceDir = new URL('../docs/overnight/evidence/import-onboarding/', import.meta.url).pathname
mkdirSync(evidenceDir, { recursive: true })
function assert(condition, message) { if (!condition) throw new Error(message) }
async function shot(page, name) { await page.screenshot({ path: `${evidenceDir}${name}`, fullPage: true }) }
async function openSettings(page) { const button = page.getByRole('button', { name: 'SETTINGS', exact: true }); if (await button.getAttribute('aria-expanded') !== 'true') await button.click() }

const csv = 'Course,Order,Unit,Unit Length,Item Type,Title,Item Length,Content/Resources,Homework/Next Up,Important Notes\nAP Art History,1,Looking & Meaning,2 weeks,Lesson,Reading images,45 min,https://example.com/images,Compare two works,Model evidence first\nAP Art History,2,Looking & Meaning,2 weeks,Lesson,Formal analysis relay,45 min,,Bring notes,Use partner talk'

const browser = await chromium.launch({ headless: true })
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
  const page = await context.newPage()
  const runtimeErrors = []
  page.on('pageerror', (error) => runtimeErrors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') runtimeErrors.push(message.text()) })
  await page.goto(baseUrl, { waitUntil: 'networkidle' })

  assert(await page.getByRole('heading', { name: 'Arc is where your plan lives when the plan changes.' }).isVisible(), 'First run did not begin in current Arc onboarding.')
  await shot(page, '01-welcome.png')
  await page.getByRole('button', { name: 'Set up my teaching day' }).click()
  await page.locator('#school-year-label').fill('2026–27')
  await page.locator('#first-school-day').fill('2026-09-01')
  await page.locator('#last-school-day').fill('2027-05-28')
  await shot(page, '02-school-year.png')
  await page.getByRole('button', { name: 'Use this calendar' }).click()

  await page.getByRole('button', { name: 'Add a course' }).click()
  await page.locator('.class-course-title input').fill('AP Art History')
  await page.waitForTimeout(50)
  await page.reload({ waitUntil: 'networkidle' })
  assert(await page.locator('.class-course-title input').inputValue() === 'AP Art History', 'Unconfirmed onboarding typing did not survive refresh.')
  await page.getByRole('button', { name: 'Add a period or section' }).click()
  await page.getByRole('button', { name: 'Add a period or section' }).click()
  const sectionInputs = page.locator('.class-section-row input')
  await sectionInputs.nth(0).fill('Period 1')
  await sectionInputs.nth(1).fill('Period 4')
  assert(await page.locator('.class-course').count() === 1 && await sectionInputs.count() === 2, 'Repeated Sections did not stay under one Course.')
  await shot(page, '03-courses-sections.png')
  await page.getByRole('button', { name: 'Save classes' }).click()

  await page.getByRole('button', { name: 'Add planning' }).click()
  const planningBlock = page.locator('.teaching-day-block--planning')
  await planningBlock.getByRole('button', { name: /Move Planning earlier/ }).click()
  assert(await planningBlock.isVisible(), 'Planning was not represented as an explicit block.')
  await shot(page, '04-build-my-day.png')
  await planningBlock.getByLabel('Starts (optional)').fill('09:00')
  await page.getByRole('button', { name: 'Use this teaching day' }).click()
  assert(await page.getByText(/needs both a start and end time/).isVisible(), 'Partial bell times were not held as an ambiguity.')
  await shot(page, '05-bell-time-ambiguity.png')
  await planningBlock.getByLabel('Starts (optional)').fill('')
  await page.getByRole('button', { name: 'Use this teaching day' }).click()

  assert(await page.getByRole('heading', { level: 1, name: 'Day' }).isVisible(), 'Onboarding did not land in the real Day view.')
  assert(await page.getByRole('button', { name: 'Planning, planning time' }).count() === 1, 'Day did not project the explicit Planning block.')
  assert(await page.getByText('Try Capture', { exact: true }).isVisible(), 'First-use Capture prompt did not appear in Arc.')
  await shot(page, '06-first-day.png')
  await page.getByRole('textbox', { name: 'Capture thought' }).fill('Pull comparison prints for P4')
  await page.getByRole('button', { name: 'Save Capture' }).click()
  const captures = JSON.parse(await page.evaluate(() => localStorage.getItem('arc.captures.v1')))
  assert(captures.workspace.captures.some((capture) => capture.text === 'Pull comparison prints for P4'), 'First Capture did not persist immediately.')
  assert(await page.getByRole('button', { name: 'Place it' }).isVisible(), 'First-use Capture did not offer the real organize/place path.')
  await shot(page, '07-first-capture.png')
  await page.getByRole('button', { name: 'Leave it here' }).click()

  await openSettings(page)
  await page.getByRole('button', { name: 'Import curriculum' }).click()
  const before = await page.evaluate(() => ({ planning: localStorage.getItem('arc.planningWorkspace.v1'), units: localStorage.getItem('arc.units.v1'), lessons: localStorage.getItem('arc.lessons.v1') }))
  await page.getByLabel('Choose a CSV file').setInputFiles({ name: 'apah-2026.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByText('2 source rows ready for review.').waitFor()
  const afterParse = await page.evaluate(() => ({ planning: localStorage.getItem('arc.planningWorkspace.v1'), units: localStorage.getItem('arc.units.v1'), lessons: localStorage.getItem('arc.lessons.v1') }))
  assert(JSON.stringify(before) === JSON.stringify(afterParse), 'Parsing mutated canonical planning truth.')
  await shot(page, '08-import-source.png')
  await shot(page, '09-parse-result.png')
  await page.getByRole('button', { name: 'Cancel' }).click()
  const afterCancel = await page.evaluate(() => ({ planning: localStorage.getItem('arc.planningWorkspace.v1'), units: localStorage.getItem('arc.units.v1'), lessons: localStorage.getItem('arc.lessons.v1') }))
  assert(JSON.stringify(before) === JSON.stringify(afterCancel), 'Cancelling import changed canonical setup or planning truth.')
  await openSettings(page)
  await page.getByRole('button', { name: 'Import curriculum' }).click()
  const ambiguousCsv = csv.replace(',Lesson,Reading images,', ',,Reading images,')
  await page.getByLabel('Source name').fill('apah-2026.csv')
  await page.getByLabel('CSV content').fill(ambiguousCsv)
  await page.getByRole('button', { name: 'Review proposal' }).click()
  assert(await page.getByText('Choose whether this row is a Unit or Lesson.').count() > 0, 'Missing Item Type did not enter ambiguity review.')
  await shot(page, '10-ambiguity-review.png')
  await page.getByRole('button', { name: 'Back' }).click()
  await page.getByLabel('CSV content').fill(csv)
  await page.getByRole('button', { name: 'Review proposal' }).click()
  const afterReview = await page.evaluate(() => ({ planning: localStorage.getItem('arc.planningWorkspace.v1'), units: localStorage.getItem('arc.units.v1'), lessons: localStorage.getItem('arc.lessons.v1') }))
  assert(JSON.stringify(before) === JSON.stringify(afterReview), 'Review mutated canonical planning truth.')
  assert(await page.getByText('2 Lessons · unscheduled', { exact: true }).isVisible(), 'Review did not show unscheduled canonical Lesson proposal.')
  await shot(page, '11-proposed-structure.png')
  await shot(page, '12-change-preview.png')
  await page.getByLabel('Potential existing Course').selectOption({ label: 'Match AP Art History' })
  await shot(page, '13-duplicate-resolution.png')
  await page.getByRole('button', { name: 'Confirm import' }).click()
  assert(await page.getByRole('heading', { name: 'The confirmed curriculum is now in Arc.' }).isVisible(), 'Confirmed import did not produce a receipt.')
  const committed = await page.evaluate(() => ({ planning: JSON.parse(localStorage.getItem('arc.planningWorkspace.v1')).input, units: JSON.parse(localStorage.getItem('arc.units.v1')).input, lessons: JSON.parse(localStorage.getItem('arc.lessons.v1')).input }))
  assert(committed.planning.courses.length === 1, 'Explicit Course match created a duplicate Course.')
  assert(committed.units.units.length === 1 && committed.lessons.lessons.length === 2, 'Confirmed import did not commit the reviewed Unit and Lessons.')
  assert(committed.lessons.lessons.every((lesson) => lesson.plannedDate === null && lesson.importProvenance?.sourceIdentity === 'apah-2026.csv'), 'Imported Lessons lost unscheduled state or provenance.')
  await shot(page, '14-confirmed-receipt.png')
  await page.getByRole('button', { name: 'Return to Day' }).click()

  await page.reload({ waitUntil: 'networkidle' })
  assert(await page.getByRole('heading', { name: 'Arc is where your plan lives when the plan changes.' }).count() === 0, 'Returning teacher was forced back through onboarding.')
  await openSettings(page)
  await page.getByRole('button', { name: 'Teaching day & planning' }).click()
  assert(await page.locator('.teaching-day-block--planning').isVisible(), 'Explicit Planning block did not survive refresh.')
  await shot(page, '18-teaching-day-return.png')
  await page.getByRole('button', { name: 'Cancel' }).click()

  await openSettings(page)
  await page.getByRole('button', { name: 'Import curriculum' }).click()
  await page.getByLabel('Choose a CSV file').setInputFiles({ name: 'apah-2026.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByRole('button', { name: 'Review proposal' }).click()
  await page.getByLabel('Potential existing Course').selectOption({ label: 'Match AP Art History' })
  assert(await page.getByText('No write needed').count() === 3, 'Identical re-import was not recognized as unchanged.')
  await shot(page, '19-identical-reimport.png')
  await page.getByRole('button', { name: 'Confirm import' }).click()
  const reimported = await page.evaluate(() => ({ units: JSON.parse(localStorage.getItem('arc.units.v1')).input.units.length, lessons: JSON.parse(localStorage.getItem('arc.lessons.v1')).input.lessons.length }))
  assert(reimported.units === 1 && reimported.lessons === 2, 'Identical re-import duplicated canonical records.')

  await page.getByRole('button', { name: 'Return to Day' }).click()
  await openSettings(page)
  await page.getByRole('button', { name: 'Lesson library' }).click()
  await page.getByLabel('Lesson title').fill('Teacher local wording')
  await page.getByRole('button', { name: 'Save Lessons' }).click()
  await page.reload({ waitUntil: 'networkidle' })
  await openSettings(page)
  await page.getByRole('button', { name: 'Import curriculum' }).click()
  const changedCsv = csv.replace('Reading images', 'Reading images with evidence')
  await page.getByLabel('Choose a CSV file').setInputFiles({ name: 'apah-2026.csv', mimeType: 'text/csv', buffer: Buffer.from(changedCsv) })
  await page.getByRole('button', { name: 'Review proposal' }).click()
  await page.getByLabel('Potential existing Course').selectOption({ label: 'Match AP Art History' })
  assert(await page.getByText('conflict', { exact: true }).isVisible(), 'Local plus upstream edits did not produce a visible re-import conflict.')
  await page.evaluate(() => { document.documentElement.style.zoom = '2' })
  const zoom200 = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth }))
  assert(zoom200.scroll <= zoom200.width + 1, `200% import review overflowed (${zoom200.scroll} > ${zoom200.width}).`)
  await page.evaluate(() => { document.documentElement.style.zoom = '4' })
  const zoom400 = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth }))
  assert(zoom400.scroll <= zoom400.width + 1, `400% import review overflowed (${zoom400.scroll} > ${zoom400.width}).`)
  await page.evaluate(() => { document.documentElement.style.zoom = '1' })
  await page.setViewportSize({ width: 390, height: 844 })
  const narrow = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth }))
  assert(narrow.scroll <= narrow.width + 1, `390px import review overflowed (${narrow.scroll} > ${narrow.width}).`)
  await shot(page, '17-390-import-review.png')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await shot(page, '15-reimport-conflict.png')
  await page.getByLabel('Resolution for Reading images with evidence').selectOption('keep-local')
  await page.getByRole('button', { name: 'Confirm import' }).click()
  const keptTitle = await page.evaluate(() => JSON.parse(localStorage.getItem('arc.lessons.v1')).input.lessons[0].title)
  assert(keptTitle === 'Teacher local wording', 'Keep-local conflict resolution overwrote teacher truth.')

  assert(runtimeErrors.length === 0, `Import/onboarding runtime errors: ${runtimeErrors.join(' | ')}`)
  await context.close()

  const narrowContext = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true })
  const narrowPage = await narrowContext.newPage()
  await narrowPage.goto(baseUrl, { waitUntil: 'networkidle' })
  const onboardingGeometry = await narrowPage.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth }))
  assert(onboardingGeometry.scroll <= onboardingGeometry.width + 1, `390px onboarding overflowed (${onboardingGeometry.scroll} > ${onboardingGeometry.width}).`)
  await shot(narrowPage, '16-390-onboarding.png')
  await narrowContext.close()

  const importEntryContext = await browser.newContext({ viewport: { width: 1024, height: 800 } })
  const importEntryPage = await importEntryContext.newPage()
  await importEntryPage.goto(baseUrl, { waitUntil: 'networkidle' })
  await importEntryPage.getByRole('button', { name: 'Import what I already have' }).click()
  await importEntryPage.locator('#school-year-label').fill('2026–27')
  await importEntryPage.locator('#first-school-day').fill('2026-09-01')
  await importEntryPage.locator('#last-school-day').fill('2027-05-28')
  await importEntryPage.getByRole('button', { name: 'Use this calendar' }).click()
  assert(await importEntryPage.getByRole('heading', { name: 'Bring in the structure. Keep the decisions yours.' }).isVisible(), 'Import-first onboarding did not reach the shared importer after calendar truth.')
  await importEntryContext.close()
  console.log('Arc import + onboarding browser gate passed: progressive first run → explicit Planning → Day → Capture → parse/review no-write → atomic confirmed import → refresh → identical re-import.')
} finally {
  await browser.close()
}
