import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles/tokens.css'
import './styles/arc-fonts.css'
import './styles/arc-plan-shell.css'
import './styles/shell-emphasis.css'
import './styles/shell-visibility-lock.css'
import './styles/global.css'
import './styles/calendarControls.css'
import './styles/calendarReadability.css'
import './styles/planningCalendar.css'
import './styles/planningDay.css'
import './styles/planningMonth.css'
import './styles/termSetup.css'
import './styles/classSetup.css'
import './styles/teachingDaySetup.css'
import './styles/curriculumImport.css'
import './styles/onboarding.css'
import './styles/unitSetup.css'
import './styles/lessonSetup.css'
import './styles/recoveryReview.css'
import './styles/planMoveShift.css'
import './styles/sourceCalendarReview.css'
import './styles/schoolIdentitySearch.css'
import './styles/visual-reconciliation.css'
import './styles/repair-pass-1-chrome.css'
import './styles/repair-pass-2-chrome.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode><App /></React.StrictMode>,
)
